version: '3.8'

services:
  mariadb:
    image: mariadb:10.7.8
    environment:
      MARIADB_USER: mariadb
      MARIADB_PASSWORD: Password111
      MARIADB_ROOT_PASSWORD: Password111
    ports:
      - 3306:3306